In [1]:
import sys
sys.version

'3.6.1 |Anaconda 4.4.0 (64-bit)| (default, May 11 2017, 13:09:58) \n[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]'

In [2]:
import numpy as np

np.random.seed(0)
x = np.random.normal(0, 0.3, (2, 1))

X = [x]
F = np.array([[0.3, 0.5], [1, 0]])
Q = np.array([[0.5, 0],[0,0]])

for i in range(10):
    x = F @ x + np.random.multivariate_normal([0,0], Q,1).T
    X.append(x)

a, b = np.array(np.concatenate(X, axis=1))
print(a)

[ 0.5292157   0.91086056  1.85842894  1.68477292  1.3616596   1.35273853
  1.62478629  1.47766385  2.31216575  1.65385394 -0.15299735]


In [7]:
H = np.mat([1, 0])
H.shape


(1, 2)

In [9]:

p = np.random.multivariate_normal([0, 0], [[1, 0],[1, 2]], 1)
np.log(p)


array([[-0.09723869, -1.47711228]])

In [33]:
K = np.array([[1],[0.5]])
yi = 3
nu_ = [nu]
for i in range(1, 2):
    nu = np.power(K*yi, 2)
    nu_.append(nu)
    a, b = np.array(np.concatenate(nu_, axis=1))
    print(nu_)
    print(nu_[-1]+nu_[-2])


[array([[ 9.  ],
       [ 2.25]]), array([[ 9.  ],
       [ 2.25]])]
[[ 18. ]
 [  4.5]]


In [60]:
Q = np.mat([[1,0],[0,0]])
eps=np.zeros((3, 1))
eps[0:2, :] = np.random.multivariate_normal([0,0], Q, 1).T
eps[2, :] = np.random.normal(0, 1)
print(eps.shape)

(3, 1)


In [73]:
x = np.mat(np.random.normal(0, 0.3, (2, 1)))
z = np.mat([1])
x_ = np.vstack([x, z])
x_[2, 0]

1.0

In [5]:
Q = np.mat([[1, 0, 0],[0, 0, 0], [0, 0, 0.1]])
a = np.random.multivariate_normal([0,0,0], Q, 1).T
print(np.log(2))

0.69314718056


In [32]:
x = np.random.normal(0, 1, (3, 3, 3))
F = np.random.normal(0, 1, (3, 3))
print(x[:, 0, 0])
print(x)

[-0.20080851 -1.07934317  0.19718106]
[[[-0.20080851 -0.9988488  -0.74013679]
  [-0.56549781  0.47603138 -2.15806856]
  [ 1.31855102 -0.23929659 -0.24679356]]

 [[-1.07934317 -0.11422555  0.01323977]
  [-0.12194493  0.33905926 -0.58963204]
  [-0.89581576  0.54832813  0.09866745]]

 [[ 0.19718106  1.05902725 -1.02256439]
  [-0.85524046  1.25721965 -1.48288336]
  [-1.30941215  0.81786183  0.23820019]]]


In [34]:
F@x[:, 0, 0]

array([ 0.08396581, -1.52299819, -1.89899648])

In [44]:
idx = np.asanyarray(range(100))
idx.shape
u0 = np.random.uniform(0, 1/100)
u0

0.0025052058641717857

In [45]:
np.cumsum(idx)

array([   0,    1,    3,    6,   10,   15,   21,   28,   36,   45,   55,
         66,   78,   91,  105,  120,  136,  153,  171,  190,  210,  231,
        253,  276,  300,  325,  351,  378,  406,  435,  465,  496,  528,
        561,  595,  630,  666,  703,  741,  780,  820,  861,  903,  946,
        990, 1035, 1081, 1128, 1176, 1225, 1275, 1326, 1378, 1431, 1485,
       1540, 1596, 1653, 1711, 1770, 1830, 1891, 1953, 2016, 2080, 2145,
       2211, 2278, 2346, 2415, 2485, 2556, 2628, 2701, 2775, 2850, 2926,
       3003, 3081, 3160, 3240, 3321, 3403, 3486, 3570, 3655, 3741, 3828,
       3916, 4005, 4095, 4186, 4278, 4371, 4465, 4560, 4656, 4753, 4851,
       4950])

In [49]:
def F_inv(w_cumsum, dx, u):
        if np.any(w_cumsum < u) == False:
            return 0
        k = np.maz(idx[w_cumsum < u])
        return k+1

In [ ]:
k_list = np.zeros(100, dtype=np.int32)
k_list.shape
for i, u in enumurate(np.random.uniform(0, 1, size=100)):
    k = 